add tests for product endpoints
nantonov/IVCRM pull request #32
Opened 2022-11-29 14:30 UTC by Genresal

2022-11-30 08:43 UTC, moltenessence approved these changes

2022-11-30 08:47 UTC, GodlyCat requested changes

2022-11-30 08:47 UTC, GodlyCat commented on Services/ProductService/IVCRM.API.IntegrationTests/ApiTests/ProductControllerTests.cs
> +            actualResult.StatusCode.Should().Be(HttpStatusCode.OK);
you could use ShouldBe instead of Should().Be, same with Should().BeEquivalentTo

2022-12-01 13:53 UTC, Genresal commented on Services/ProductService/IVCRM.API.IntegrationTests/ApiTests/ProductControllerTests.cs
> +            actualResult.StatusCode.Should().Be(HttpStatusCode.OK);
Unfortunately FluentAssertions library does not have ShoulBe() constructions, only Should().Be(), should I replace FluentAssertions with another library or...
https://fluentassertions.com/basicassertions/

2022-12-01 14:45 UTC, GodlyCat commented on Services/ProductService/IVCRM.API.IntegrationTests/ApiTests/ProductControllerTests.cs
> +            actualResult.StatusCode.Should().Be(HttpStatusCode.OK);
Use Shouldly for tests

2022-12-07 10:43 UTC, nantonov approved these changes

2022-12-08 07:39 UTC, GodlyCat approved these changes

2022-12-08 07:44 UTC, merged