create customer controller
nantonov/IVCRM pull request #4
Opened 2022-10-26 12:55 UTC by Genresal

2022-10-26 13:19 UTC, nantonov requested changes

2022-10-26 13:19 UTC, nantonov commented on IVCRM.API/Controllers/CustomerController.cs
> +        public async Task<IActionResult> Update([FromBody] UpdateCustomerRequest request)
Send id in route, not in body

2022-10-26 23:48 UTC, stas1408123 requested changes

2022-10-26 23:48 UTC, stas1408123 commented on IVCRM.BLL/Services/CustomerService.cs
> +            var responce =  await _customerRepository.Create(mappedRequest);
response

2022-10-26 23:48 UTC, stas1408123 commented on IVCRM.DAL/Repositories/CustomerRepository.cs
> +        public async Task<CustomerEntity> Create(CustomerEntity request)
request?

2022-10-26 23:48 UTC, stas1408123 commented on IVCRM.DAL/Repositories/CustomerRepository.cs
> +        public async Task<CustomerEntity?> Update(CustomerEntity request)
Use method update attach from ef

2022-10-27 08:41 UTC, Blackolf931 requested changes

2022-10-27 08:41 UTC, Blackolf931 commented on IVCRM.DAL/Repositories/CustomerRepository.cs
> +            }
move this logic to bll

2022-10-27 08:41 UTC, Blackolf931 commented on IVCRM.DAL/Repositories/CustomerRepository.cs
> +            }
move this logic to bll

2022-10-27 08:41 UTC, Blackolf931 commented on IVCRM.DAL/Repositories/CustomerRepository.cs
> +            existsEntity.PhoneNumber = entity.PhoneNumber;
move to bll

2022-10-27 08:41 UTC, Blackolf931 commented on IVCRM.DAL/Repositories/CustomerRepository.cs
> +            existsEntity.PhoneNumber = entity.PhoneNumber;
in dal layer we only work with data f.e get, add and etc, all logic should be on bll layer

2022-10-27 08:41 UTC, Blackolf931 commented on IVCRM.DAL/Repositories/CustomerRepository.cs
> +            _context.Customers.Attach(existsEntity);
Why you use 'Attach' here? you can use _context.Customer.Update(customerEntity)

2022-10-27 08:41 UTC, Blackolf931 commented on IVCRM.DAL/Repositories/CustomerRepository.cs
> +            return await _context.Customers.SingleOrDefaultAsync(x => x.Id == id);
Why you use SingleOrDefault? You can use FirstOrdefault

2022-10-27 08:41 UTC, Blackolf931 commented on IVCRM.BLL/Profiles/BllMappingProfile.cs
> +            CreateMap<Customer, CustomerEntity>().ReverseMap();
move this logic to constructor

2022-10-27 08:41 UTC, Blackolf931 commented on IVCRM.API/RequestModels/UpdateCustomerRequest.cs
> +        [Required]
please explain how it would be work if we have Required attribute and '?'

2022-10-27 08:41 UTC, Blackolf931 commented on IVCRM.API/Profiles/ApiMappingProfile.cs
> +            CreateMap<UpdateCustomerRequest, Customer>();
move this logic to constructor

2022-10-27 08:41 UTC, Blackolf931 commented on IVCRM.API/Controllers/CustomerController.cs
> +        public async Task<IActionResult> Update(int id, [FromBody] UpdateCustomerRequest request)
Why you use IActionResult instead of Task<f.e customerViewModel>

2022-10-27 08:41 UTC, Blackolf931 commented on IVCRM.API/Controllers/CustomerController.cs
> +        public async Task<IActionResult> Update(int id, [FromBody] UpdateCustomerRequest request)
What about naming 'UpdateCustomerRequest request' you can use 'UpdateCustomerRequest updateCustomerViewModel'

2022-10-27 08:41 UTC, Blackolf931 commented on IVCRM.API/Controllers/CustomerController.cs
> +            }
this logic should be here?

2022-10-27 08:41 UTC, Blackolf931 commented on IVCRM.API/Controllers/CustomerController.cs
> +            }
For future this logic is implemented in validators(leave it here for now)

2022-10-27 08:41 UTC, Blackolf931 commented on IVCRM.API/Controllers/CustomerController.cs
> +            }
This logic should be here?

2022-10-27 08:41 UTC, Blackolf931 commented on IVCRM.API/Controllers/CustomerController.cs
> +        public async Task<IActionResult> GetById(int id)
IActionResult change to model type

2022-10-27 08:41 UTC, Blackolf931 commented on IVCRM.API/Controllers/CustomerController.cs
> +        public async Task<IActionResult> GetAll()
IActionResult change to model type

2022-10-27 08:41 UTC, Blackolf931 commented on IVCRM.API/Controllers/CustomerController.cs
> +            }
this logic should be here? i think it should be on Bll layer

2022-10-27 08:41 UTC, Blackolf931 commented on IVCRM.API/Controllers/CustomerController.cs
> +        public async Task<IActionResult> Create(CreateCustomerRequest request)
IActionResult change to model type

2022-10-27 08:53 UTC, Blackolf931 requested changes

2022-10-27 08:53 UTC, Blackolf931 commented on IVCRM.API/RequestModels/CreateCustomerRequest.cs
> +    public class CreateCustomerRequest
move it to view model folder and rename it f.e ChangeCustomerViewModel and you can use new model for post and update methods

2022-10-27 11:17 UTC, Genresal commented on IVCRM.API/RequestModels/UpdateCustomerRequest.cs
> +        [Required]
Obviously nothing

2022-10-27 11:40 UTC, Blackolf931 requested changes

2022-10-27 11:40 UTC, Blackolf931 commented on IVCRM.BLL/Services/CustomerService.cs
> +            var response = await _customerRepository.Update(entity);
rename 'response' to entity and see this in other cases

2022-10-27 11:40 UTC, Blackolf931 commented on IVCRM.BLL/Services/CustomerService.cs
> +            }
Is it logic correct?

2022-10-27 12:08 UTC, nantonov requested changes

2022-10-27 12:46 UTC, stas1408123 approved these changes

2022-10-27 12:48 UTC, stas1408123 approved these changes

2022-10-27 12:48 UTC, stas1408123 commented on IVCRM.API/Controllers/CustomerController.cs
> +        public async Task<CustomerViewModel> Update(int id, [FromBody] ChangeCustomerViewModel viewModel)
сhangeCustomerViewModel

2022-10-27 12:48 UTC, stas1408123 commented on IVCRM.BLL/Services/CustomerService.cs
> +        public async Task<Customer> Update(Customer model)
customer

2022-10-27 12:48 UTC, stas1408123 commented on IVCRM.DAL/Repositories/CustomerRepository.cs
> +        public async Task<CustomerEntity?> Update(CustomerEntity entity)
customerEntity

2022-10-28 07:33 UTC, stas1408123 approved these changes

2022-10-28 07:49 UTC, Blackolf931 approved these changes

2022-10-28 11:16 UTC, nantonov approved these changes

2022-10-28 11:16 UTC, merged