Cover api by tests
nantonov/IVCRM pull request #8
Opened 2022-10-31 09:59 UTC by Genresal

2022-10-31 14:48 UTC, Blackolf931 requested changes

2022-10-31 14:48 UTC, Blackolf931 commented on IVCRM.API.IntegrationTests/ApiTests/CustomerControllerTests.cs
> +            }
use AddRange instead of await AddToContext(entityCollection[i]);

2022-10-31 15:08 UTC, nantonov approved these changes

2022-11-01 07:42 UTC, Blackolf931 approved these changes

2022-11-01 07:42 UTC, merged